table Dim_Turmas
	lineageTag: b1ecd353-5e0e-4617-b044-8bf8746eead9

	column cod_turma
		dataType: int64
		formatString: 0
		lineageTag: 4e3ca09c-83da-4b3a-b19c-3d8cf1345fa5
		summarizeBy: none
		sourceColumn: cod_turma

		annotation SummarizationSetBy = Automatic

	column nome_turma
		dataType: string
		lineageTag: 92db6cf5-d78c-4945-9f15-aece68db4ca1
		summarizeBy: none
		sourceColumn: nome_turma

		annotation SummarizationSetBy = Automatic

	column modalidade_turma
		dataType: string
		lineageTag: 4af4ff23-c697-43a9-bb34-19b56294bcff
		summarizeBy: none
		sourceColumn: modalidade_turma

		annotation SummarizationSetBy = Automatic

	column dt_fim
		dataType: dateTime
		formatString: General Date
		lineageTag: f9cf0247-444b-4537-8837-42e11b85196f
		summarizeBy: none
		sourceColumn: dt_fim

		variation Variation
			isDefault
			relationship: 7e1c1948-6bfd-44a0-ada8-94d64ebd0a81
			defaultHierarchy: LocalDateTable_e33d10c6-cf04-4790-9059-a4c32c2277ee.'Hierarquia de datas'

		annotation SummarizationSetBy = Automatic

	column sit_turma
		dataType: string
		lineageTag: 269847b1-5f64-4783-8018-90ca64576b07
		summarizeBy: none
		sourceColumn: sit_turma

		annotation SummarizationSetBy = Automatic

	partition Dim_Turmas = m
		mode: import
		source =
				let
				    Fonte = sample_evg_enriquecido,
				    #"Outras Colunas Removidas" = Table.SelectColumns(Fonte,{"cod_turma", "nome_turma", "modalidade_turma", "dt_fim", "sit_turma"}),
				    #"Duplicatas Removidas" = Table.Distinct(#"Outras Colunas Removidas", {"cod_turma"}),
				    #"Tipo Alterado" = Table.TransformColumnTypes(#"Duplicatas Removidas",{{"cod_turma", Int64.Type}})
				in
				    #"Tipo Alterado"

	annotation PBI_NavigationStepName = Navegação

	annotation PBI_ResultType = Table

